#!/bin/bash

# Author: Federico De Rocco
# Date Created: 17/02/2024
# Last Modified: 17/02/2024
# Description: Backup files in home
# Usage: 
# backup_script

tar -cvf ~/bash_course/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null

exit 0
