#!/bin/bash

# Author: Federico De Rocco
# Date Created: 17/02/2024
# Last Modified: 17/02/2024
# Description: Backup files in home
# Usage: 
# backup_script


echo "Hello, ${USER^}"
echo "I will now back up your home directory, $HOME"

currentdir=$(pwd)

echo "You are running this script from $currentdir"
echo "Therefore, I will save the backup in $currentdir"

tar -cf $currentdir/bash_course/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null

echo "Backup Completed Successfully."
exit 0
