#!/bin/bash

# Author: Federico De Rocco
# Date Created: 17/02/2024
# Last Modified: 17/02/2024

# Description
# Prints "This is my first script" on the terminal

# Usage
# our_first_script

echo "This is my first script"
exit 0
